#!/bin/sh

pkg update && pkg upgrade
pkg i bash cmake make vim clang git binutils
pkg install python3

curl -o NspUpdaterRun https://raw.githubusercontent.com/alfhashut/file-storage/main/NspUpdaterRun
chmod +x NspUpdaterRun
curl -o menü.py https://raw.githubusercontent.com/alfhashut/file-storage/main/menü.py
git clone https://github.com/SciresM/hactool
mv hactool hactoolsrc
cd hactoolsrc
git checkout c2c907430e674614223959f0377f5e71f9e44a4a
mv config.mk.template config.mk
sed -i '372d' main.c
mv main.temp main.c
make
mv hactool ..
cd ..

git clone https://github.com/The-4n/hacPack
cd hacPack
git checkout 7845e7be8d03a263c33430f9e8c2512f7c280c88
mv config.mk.template config.mk
make
mv hacpack ..
cd ..
